name: Scrape confluence
url: file:///Users/maurosciancalepore/Downloads/text2.html
out_dir: confluence_scraping
headless: true
timeout: 5
targets:
  paragraphs: 
    selector: "//*[self::p and not(ancestor::li) and not(ancestor::table) or self::ul or self::h2]"
  lists: 
    selector: "//ul"
actions:
  save1:
    flatten: false
    targets: 
      - paragraphs
steps:
  - paragraphs
  - save1